from typing import TypeVar

from django.db.models import Manager, Model, QuerySet
from returns.future import FutureResult
from returns.io import IOResult
from returns.maybe import Maybe
from returns.result import Result

_M = TypeVar("_M", bound=Model)

class BaseReturnsQuerySet(QuerySet[_M]):
    """Base QuerySet with list of unsafe methods."""

    UNSAFE_METHODS: list[str]

class ExtendedReturnsQuerySet(BaseReturnsQuerySet[_M]):
    """A subclass that includes safe versions (ending with _result or _ioresult)
    of unsafe methods that can be used separately from the original methods.
    """

    # Sync methods: return Result (safe)
    def get_result(self, *args, **kwargs) -> Result[_M, Exception]: ...
    def earliest_result(self, *args, **kwargs) -> Result[_M, Exception]: ...
    def latest_result(self, *args, **kwargs) -> Result[_M, Exception]: ...
    def create_result(self, *args, **kwargs) -> Result[_M, Exception]: ...
    def get_or_create_result(
        self, *args, **kwargs
    ) -> Result[tuple[_M, bool], Exception]: ...
    def update_or_create_result(
        self, *args, **kwargs
    ) -> Result[tuple[_M, bool], Exception]: ...
    def delete_result(
        self, *args, **kwargs
    ) -> Result[tuple[int, dict[str, int]], Exception]: ...
    def bulk_create_result(self, *args, **kwargs) -> Result[list[_M], Exception]: ...

    # Sync methods: return IOResult (impure_safe)
    def get_ioresult(self, *args, **kwargs) -> IOResult[_M, Exception]: ...
    def earliest_ioresult(self, *args, **kwargs) -> IOResult[_M, Exception]: ...
    def latest_ioresult(self, *args, **kwargs) -> IOResult[_M, Exception]: ...
    def create_ioresult(self, *args, **kwargs) -> IOResult[_M, Exception]: ...
    def get_or_create_ioresult(
        self, *args, **kwargs
    ) -> IOResult[tuple[_M, bool], Exception]: ...
    def update_or_create_ioresult(
        self, *args, **kwargs
    ) -> IOResult[tuple[_M, bool], Exception]: ...
    def delete_ioresult(
        self, *args, **kwargs
    ) -> IOResult[tuple[int, dict[str, int]], Exception]: ...
    def bulk_create_ioresult(
        self, *args, **kwargs
    ) -> IOResult[list[_M], Exception]: ...

    # Async methods: return FutureResult (future_safe - returns awaitable, not coroutine)
    # These are NOT declared as async because future_safe returns a function that returns FutureResult
    def aget_ioresult(self, *args, **kwargs) -> FutureResult[_M, Exception]: ...
    def aearliest_ioresult(self, *args, **kwargs) -> FutureResult[_M, Exception]: ...
    def alatest_ioresult(self, *args, **kwargs) -> FutureResult[_M, Exception]: ...
    def acreate_ioresult(self, *args, **kwargs) -> FutureResult[_M, Exception]: ...
    def aget_or_create_ioresult(
        self, *args, **kwargs
    ) -> FutureResult[tuple[_M, bool], Exception]: ...
    def aupdate_or_create_ioresult(
        self, *args, **kwargs
    ) -> FutureResult[tuple[_M, bool], Exception]: ...
    def adelete_ioresult(
        self, *args, **kwargs
    ) -> FutureResult[tuple[int, dict[str, int]], Exception]: ...
    def abulk_create_ioresult(
        self, *args, **kwargs
    ) -> FutureResult[list[_M], Exception]: ...

    # Maybe methods
    def first_maybe(self, *args, **kwargs) -> Maybe[_M]: ...
    def last_maybe(self, *args, **kwargs) -> Maybe[_M]: ...

class ReturnsManager(Manager[_M]):
    """Manager that selects a QuerySet according to init params
    and defaults to ExtendedReturnsQuerySet.
    """
    def __init__(
        self,
        *args,
        **kwargs,
    ) -> None: ...
    def get_queryset(
        self,
    ) -> ExtendedReturnsQuerySet[_M]: ...

    # Sync Result methods
    def get_result(self, *args, **kwargs) -> Result[_M, Exception]: ...
    def earliest_result(self, *args, **kwargs) -> Result[_M, Exception]: ...
    def latest_result(self, *args, **kwargs) -> Result[_M, Exception]: ...
    def create_result(self, *args, **kwargs) -> Result[_M, Exception]: ...
    def get_or_create_result(
        self, *args, **kwargs
    ) -> Result[tuple[_M, bool], Exception]: ...
    def update_or_create_result(
        self, *args, **kwargs
    ) -> Result[tuple[_M, bool], Exception]: ...
    def delete_result(
        self, *args, **kwargs
    ) -> Result[tuple[int, dict[str, int]], Exception]: ...
    def bulk_create_result(self, *args, **kwargs) -> Result[list[_M], Exception]: ...

    # Sync IOResult methods
    def get_ioresult(self, *args, **kwargs) -> IOResult[_M, Exception]: ...
    def earliest_ioresult(self, *args, **kwargs) -> IOResult[_M, Exception]: ...
    def latest_ioresult(self, *args, **kwargs) -> IOResult[_M, Exception]: ...
    def create_ioresult(self, *args, **kwargs) -> IOResult[_M, Exception]: ...
    def get_or_create_ioresult(
        self, *args, **kwargs
    ) -> IOResult[tuple[_M, bool], Exception]: ...
    def update_or_create_ioresult(
        self, *args, **kwargs
    ) -> IOResult[tuple[_M, bool], Exception]: ...
    def delete_ioresult(
        self, *args, **kwargs
    ) -> IOResult[tuple[int, dict[str, int]], Exception]: ...
    def bulk_create_ioresult(
        self, *args, **kwargs
    ) -> IOResult[list[_M], Exception]: ...

    # Async FutureResult methods
    def aget_ioresult(self, *args, **kwargs) -> FutureResult[_M, Exception]: ...
    def aearliest_ioresult(self, *args, **kwargs) -> FutureResult[_M, Exception]: ...
    def alatest_ioresult(self, *args, **kwargs) -> FutureResult[_M, Exception]: ...
    def acreate_ioresult(self, *args, **kwargs) -> FutureResult[_M, Exception]: ...
    def aget_or_create_ioresult(
        self, *args, **kwargs
    ) -> FutureResult[tuple[_M, bool], Exception]: ...
    def aupdate_or_create_ioresult(
        self, *args, **kwargs
    ) -> FutureResult[tuple[_M, bool], Exception]: ...
    def adelete_ioresult(
        self, *args, **kwargs
    ) -> FutureResult[tuple[int, dict[str, int]], Exception]: ...
    def abulk_create_ioresult(
        self, *args, **kwargs
    ) -> FutureResult[list[_M], Exception]: ...

    # Maybe methods
    def first_maybe(self, *args, **kwargs) -> Maybe[_M]: ...
    def last_maybe(self, *args, **kwargs) -> Maybe[_M]: ...

class MaybeReturnsQuerySet(BaseReturnsQuerySet[_M]):
    """Experimental: a subclass that includes Maybe-returning methods."""
    def first(self, *args, **kwargs) -> Maybe[_M]: ...
    def last(self, *args, **kwargs) -> Maybe[_M]: ...

class SafeReturnsQuerySet(MaybeReturnsQuerySet[_M]):
    """Experimental: a subclass that overrides unsafe methods
    to return Result instead of raising exceptions.
    """
    def get(self, *args, **kwargs) -> Result[_M, Exception]: ...
    def earliest(self, *args, **kwargs) -> Result[_M, Exception]: ...
    def latest(self, *args, **kwargs) -> Result[_M, Exception]: ...
    def create(self, *args, **kwargs) -> Result[_M, Exception]: ...
    def get_or_create(self, *args, **kwargs) -> Result[tuple[_M, bool], Exception]: ...
    def update_or_create(
        self, *args, **kwargs
    ) -> Result[tuple[_M, bool], Exception]: ...
    def delete(
        self, *args, **kwargs
    ) -> Result[tuple[int, dict[str, int]], Exception]: ...
    def bulk_create(self, *args, **kwargs) -> Result[list[_M], Exception]: ...

class ImpureReturnsQuerySet(MaybeReturnsQuerySet[_M]):
    """Experimental: a subclass that overrides unsafe methods
    to return IOResult instead of raising exceptions.
    """
    def get(self, *args, **kwargs) -> IOResult[_M, Exception]: ...
    def earliest(self, *args, **kwargs) -> IOResult[_M, Exception]: ...
    def latest(self, *args, **kwargs) -> IOResult[_M, Exception]: ...
    def create(self, *args, **kwargs) -> IOResult[_M, Exception]: ...
    def get_or_create(
        self, *args, **kwargs
    ) -> IOResult[tuple[_M, bool], Exception]: ...
    def update_or_create(
        self, *args, **kwargs
    ) -> IOResult[tuple[_M, bool], Exception]: ...
    def delete(
        self, *args, **kwargs
    ) -> IOResult[tuple[int, dict[str, int]], Exception]: ...
    def bulk_create(self, *args, **kwargs) -> IOResult[list[_M], Exception]: ...
